"""Write the synthetic demo corpus to PDF files the operator can upload.

The pilot loads its documents through the product's own upload path — a file
picker in the running application — so the corpus has to exist as files on
disk. ``scripts.seed`` renders the same pages straight into a store, which is
what seeding needs and no help at all to a human in front of a file dialog.

The rendering is deterministic: fixed document metadata and ``no_new_id=True``
in :func:`scripts.seed.render_pdf`. So these files are the documents the golden
set in ``backend/eval/golden.json`` was built against, not a fresh variant that
merely says the same things. The checksum list this writes is what makes that
checkable later, when the pilot needs to answer whether the documents it
uploaded were the documents its facit describes.

Usage::

    backend/.venv/bin/python backend/scripts/export_corpus.py
    backend/.venv/bin/python backend/scripts/export_corpus.py --output-dir ~/pilot-korpus
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.seed import render_pdf  # noqa: E402
from scripts.seed_content import DOCUMENTS  # noqa: E402

CHECKSUMS = "korpus.sha256"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path.home() / "pilot-korpus",
        # Outside the checkout on purpose: these are generated bytes with a
        # generator in version control, and the repository is not where the
        # operator picks files from anyway.
        help="Where to write the PDFs (default: ~/pilot-korpus, outside the checkout)",
    )
    args = parser.parse_args()

    output_dir: Path = args.output_dir.expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    lines = []
    for document in DOCUMENTS:
        name = document["name"]
        data = render_pdf(document)
        target = output_dir / name
        # Deterministic output means a re-run is a verification, not a change:
        # say so, because "unchanged" is the interesting outcome.
        previous = target.read_bytes() if target.is_file() else None
        target.write_bytes(data)
        digest = hashlib.sha256(data).hexdigest()
        state = "ny" if previous is None else ("oförändrad" if previous == data else "ERSATT")
        pages = len(document["pages"])
        print(f"  {digest}  {len(data):>7} byte  {pages} sid  {state:<11} {name}")
        lines.append(f"{digest}  {name}")

    (output_dir / CHECKSUMS).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n{len(DOCUMENTS)} dokument i {output_dir}")
    print(f"Kontrollsummor: {output_dir / CHECKSUMS}  (verifiera med: sha256sum -c {CHECKSUMS})")


if __name__ == "__main__":
    main()
